ignore-paths:
  - clearCNV/_version.py
  - versioneer.py

pep257:
  disable:
    - D100
    - D101
    - D102
    - D103
    - D104
    - D105
    - D107
    - D202
    - D203
    - D204
    - D213

pep8:
  disable:
    - E741

pylint:
  disable:
    - too-many-statements
    - too-many-arguments
    - no-else-return
    - too-many-locals
    - import-error
