workdir: '.'
metafile: '/fast/work/users/vmay_m/workflow/FCC/UNTANGLING/run_003/meta_SDAG2.tsv'
coverages: '/fast/work/users/vmay_m/workflow/FCC/UNTANGLING/run_003/coverages.tsv'
cov_dir: '/fast/work/users/vmay_m/workflow/FCC/UNTANGLING/run_003/covs'
bedfile: '/fast/work/users/vmay_m/workflow/FCC/UNTANGLING/run_003/union.bed'
bamsfile: '/fast/work/users/vmay_m/workflow/FCC/UNTANGLING/run_003/allbams.txt'
reference: '/fast/work/projects/cubit/18.12/static_data/reference/GRCh37/hs37d5/hs37d5.fa'
