workdir: 'tests/testdata/'
metafile: '/fast/work/users/vmay_m/development/clearCNV/tests/testdata/test_untangle_meta.tsv'
coverages: '/fast/work/users/vmay_m/development/clearCNV/tests/testdata/test_untangling_coverages.tsv'
cov_dir: '/fast/work/users/vmay_m/development/clearCNV/tests/testdata/covs'
bedfile: '/fast/work/users/vmay_m/development/clearCNV/tests/testdata/test_untangling_union.bed'
bamsfile: '/fast/work/users/vmay_m/development/clearCNV/tests/testdata/allbams.txt'
reference: '/fast/work/users/vmay_m/development/clearCNV/tests/testdata/test_untangling_ref.fa'
