workdir: '/fast/work/users/vmay_m/workflow/FCC/UNTANGLING/run_002'
metafile: '/fast/work/users/vmay_m/workflow/FCC/UNTANGLING/run_001/meta.tsv'
coverages: '/fast/work/users/vmay_m/workflow/FCC/UNTANGLING/run_002/coverages.tsv'
cov_dir: '/fast/work/users/vmay_m/workflow/FCC/UNTANGLING/run_002/covs'
bedfile: '/fast/work/users/vmay_m/workflow/FCC/UNTANGLING/run_002/union.bed'
bamsfile: '/fast/work/users/vmay_m/workflow/FCC/UNTANGLING/run_002/allbams.txt'
reference: '/fast/work/projects/cubit/18.12/static_data/reference/GRCh37/hs37d5/hs37d5.fa'
