workdir: 'tests/testdata/'
metafile: '/fast/work/users/vmay_m/development/test_ccnv/clear-cnv/tests/testdata/test_reassign_meta.tsv'
coverages: '/fast/work/users/vmay_m/development/test_ccnv/clear-cnv/tests/testdata/test_reassignment_coverages.tsv'
cov_dir: '/fast/work/users/vmay_m/development/test_ccnv/clear-cnv/tests/testdata/covs'
bedfile: '/fast/work/users/vmay_m/development/test_ccnv/clear-cnv/tests/testdata/test_reassignment_union.bed'
bamsfile: '/fast/work/users/vmay_m/development/test_ccnv/clear-cnv/tests/testdata/allbams.txt'
reference: '/fast/work/users/vmay_m/development/test_ccnv/clear-cnv/tests/testdata/test_reassignment_ref.fa'
