workdir: 'SDAG_1'
panelname: 'SDAG2_1'
bedfile: '../beds/SDAG2.bed'
bamsfile: '/fast/work/users/vmay_m/workflow/FCC/UNTANGLING/run_003/assignments/SDAG2_batch01_2.txt'
reference: '/fast/work/projects/cubit/18.12/static_data/reference/GRCh37/hs37d5/hs37d5.fa'
kmer_align: '/fast/work/projects/cubit/18.12/static_data/db/goldenpath/variable/GRCh37/wgEncodeCrgMapabilityAlign50mer.eq_1.bed'
expected_artefacts: '0.02'
sample_score_factor: '2.0'
minimum_group_sizes: '20'
zscale: '0.65'
size: '2000'
del_cutoff: '0.75'
dup_cutoff: '1.35'
trans_prob: '0.001'
plot_regions: 'True'
