workdir: '/fast/users/vmay_m/work/workflow/FCC/CALLING/'
panelname: 'BM'
bedfile: '/fast/users/vmay_m/work/workflow/beds/nosex/BM.bed'
bamsfile: '/fast/users/vmay_m/work/workflow/bams/reassignd/BM_bams.txt'
reference: '/fast/work/projects/cubit/18.12/static_data/reference/GRCh37/hs37d5/hs37d5.fa'
kmer_align: '/fast/work/projects/cubit/18.12/static_data/db/goldenpath/variable/GRCh37/wgEncodeCrgMapabilityAlign36mer.eq_1.bed'
expected_artefacts: '0.02'
minimum_sample_score: '0.15'
minimum_group_sizes: '30'
sensitivity: '0.75'
size: '2000'
