name: continuous integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"

    steps:
      - name: Install Python via conda.
        uses: s-weigand/setup-conda@v1
        with:
          python-version: ${{ matrix.python-version }}
          conda-channels: defaults,bioconda,conda-forge
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Install mamba.
        run: conda install -y mamba
      - name: Install external program dependencies.
        run: mamba install -y bedtools
      - name: Install large dependencies with mamba to speedup vs. pip
        run: mamba install -y pandas matplotlib scikit-learn snakemake
      - name: Install test dependencies via pip
        run: pip install -r requirements/test.txt
      - name: Install test dependencies via pip (black only on Python 3.8)
        run: pip install -r requirements/test_black.txt
        if: ${{ matrix.python-version == '3.8' }}
      - name: Run tests
        run: pytest .
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
        if: ${{ matrix.python-version == '3.8' }}
      - name: Check style with black (only on Python 3.8)
        run: black --line-length 100 --check .
        if: ${{ matrix.python-version == '3.8' }}
