name: continuous integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - name: Install Python via conda.
        uses: s-weigand/setup-conda@v1
        with:
          python-version: ${{ matrix.python-version }}
          conda-channels: defaults,bioconda,conda-forge
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Install test dependencies
        run: pip install -r requirements/test.txt
      - name: Check style with black
        run: black --line-length 100 --check .
